version: '3.9'

services:
  database:
    image: postgres
    container_name: emdb
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=easymarket
      - POSTGRES_PASSWORD=easymarket
      - POSTGRES_DB=easymarket
      - DB_EXTENSION=uuid-ossp
    volumes:
      - empgdata:/data/postgres/emdb

  app:
    build: .
    container_name: emapi
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app/emapi
    links:
      - database
    depends_on:
      - database

volumes:
  empgdata:
    driver: local
